mounts:
  # assets
  - source: node_modules/bootstrap/dist/js
    target: assets/assets/js/bootstrap
  - source: node_modules/jquery/dist
    target: assets/assets/js/jquery
  - source: assets
    target: assets
  # content
  - source: content
    target: content
  # static
  - source: node_modules/@fontsource-variable/inter/files
    target: static/assets/fonts
  - source: static
    target: static
